### ISSUE TITLE
好久不见海峰

### ISSUE THREAD

**Issue by zhangzl419** [oaksharks/foo#2]
哈哈，还好吗？

**Comment by oaksharks** [comment]
@zhangzl419 Issue  还能干这个？！
![924134b6d1611b662381267d1040f37](https://github.com/oaksharks/foo/assets/7763696/a161bf04-eebc-46a5-b7c0-460597751846)

**Comment by zhangzl419** [comment]
你还在写代码？哈哈
![004BFC74](https://github.com/oaksharks/foo/assets/3785968/58e9eef5-b97c-492c-9f8f-34dc619364c7)

**Comment by zhangzl419** [comment]
我看到你的github账号，就想怎么给你打个招呼，找了半天，最后想到issue了

**Comment by oaksharks** [comment]
还有别的通信工具，比如这个zhangzl419@163.com，邮箱见。
